// Flutter imports:
import 'package:flutter/material.dart';

/// Represents a user-configurable parameter.
///
/// Implementations of this class are responsible for defining how the parameter's
/// value is obtained from the user and stored.
abstract class UserParameter {
  /// A unique identifier for this parameter.
  final String key;

  /// A map used to store the value of this parameter.
  ///
  /// The value associated with [key] in this map will be updated
  /// by the widget generated by [getInputWidget].
  final Map<String, dynamic> parameterValueStorage;

  /// Creates a new instance of [UserParameter].
  ///
  /// [key] is the unique identifier for this parameter.
  /// [parameterValueStorage] is the map where the parameter's value will be stored.
  UserParameter(this.key, this.parameterValueStorage);

  /// Generates a widget that allows the user to input a value for this parameter.
  ///
  /// The generated widget should handle user input and update the
  /// [parameterValueStorage] map with the new value, using [key] as the map key.
  ///
  /// For example, an implementation for a text input might return a `TextField`
  /// widget. When the text changes, the `onChanged` callback of the `TextField`
  /// would update `parameterValueStorage[key]` with the new text.
  Widget getInputWidget();
}
