# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sort_imports:
    runs-on: ubuntu-latest
    # This job now uses a token with write permissions
    permissions:
      contents: write  # This is the key addition - grant write permission to repository contents

    steps:
      - uses: actions/checkout@v4
        with:
          # This is needed to ensure we have full git history for commits
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in token

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or 'beta', 'dev'

      - name: Install import_sorter
        run: flutter pub add import_sorter --dev

      - name: Sort imports
        run: flutter pub run import_sorter:main

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatically sort imports"
          # Push to the same branch that triggered the workflow
          git push


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or 'beta', 'dev'

      - name: Install dependencies
        run: flutter pub get

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze --fatal-infos

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
#      - name: Run tests
#        run: flutter test
